#!/usr/bin/env python3
"""
Flash-P version utility.

Primary source of truth is LIVE git state (git describe), so every value this
returns automatically reflects the actual commit/tag being run -- never a
hand-typed literal that can go stale. Falls back to a static VERSION file only
when .git is unavailable (e.g. a distributed/zipped copy with no git history);
that file is regenerated by Agent/shared/cut_release.py at every tagged
release, never hand-edited.

All output-producing scripts should call get_version() and stamp it into
their outputs.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Optional

_HERE = Path(__file__).parent
_VERSION_FILE = _HERE / "VERSION"          # sole canonical fallback file
_GIT_TIMEOUT = 3  # seconds -- never let a stalled git call hang the pipeline

_cache: Optional[dict] = None              # computed once per process


def _run_git(args: list) -> Optional[str]:
    """Run a git command rooted at this file's tree; None on ANY failure (never raises)."""
    try:
        r = subprocess.run(
            ["git", *args], cwd=_HERE, capture_output=True, text=True,
            timeout=_GIT_TIMEOUT,
        )
    except Exception:
        return None
    if r.returncode != 0:
        return None
    return r.stdout.strip()


def _strip_v(tag_ish: str) -> str:
    """'v1.0.0...' -> '1.0.0...'; leaves bare-SHA fallbacks (no leading 'vDIGIT') untouched."""
    return tag_ish[1:] if re.match(r"^v\d", tag_ish) else tag_ish


def _compute() -> dict:
    describe = _run_git(["describe", "--tags", "--always", "--dirty"])
    if describe is not None:
        sha = _run_git(["rev-parse", "--short", "HEAD"]) or ""
        sha_full = _run_git(["rev-parse", "HEAD"]) or ""
        exact = _run_git(["describe", "--tags", "--exact-match"]) is not None
        dirty = describe.endswith("-dirty")
        return {
            "flash_p_version": _strip_v(describe),
            "git_commit": sha,
            "git_commit_full": sha_full,
            "is_release": exact and not dirty,
            "dirty": dirty,
            "source": "git",
        }
    if _VERSION_FILE.exists():
        v = _VERSION_FILE.read_text(encoding="utf-8").strip()
        return {
            "flash_p_version": v or "unknown", "git_commit": "", "git_commit_full": "",
            "is_release": False, "dirty": False, "source": "file",
        }
    return {
        "flash_p_version": "unknown", "git_commit": "", "git_commit_full": "",
        "is_release": False, "dirty": False, "source": "unknown",
    }


def _info() -> dict:
    global _cache
    if _cache is None:
        _cache = _compute()
    return _cache


def get_version() -> str:
    """Current Flash-P version: live git tag/describe string, bare (no 'v' prefix),
    or the static VERSION-file fallback, or "unknown". See module docstring."""
    return _info()["flash_p_version"]


def get_version_info() -> dict:
    """Full version metadata for embedding in JSON outputs / the Studio.

    Keys: flash_p_version, git_commit (short SHA), git_commit_full, is_release
    (exactly on a tag with a clean working tree), dirty, source ("git"/"file"/"unknown").
    """
    return dict(_info())  # copy -- callers must not mutate the cache


if __name__ == "__main__":
    import sys

    info = get_version_info()
    if "--bare" in sys.argv:
        # Just the raw version string -- the value to paste into a metadata block.
        print(info["flash_p_version"])
    else:
        print(
            f"Flash-P v{info['flash_p_version']} "
            f"({'release' if info['is_release'] else 'dev build'}"
            f"{', dirty' if info['dirty'] else ''}, source={info['source']})"
        )
